# .install_dependencies:
#   before_script:
build-linux:
  tags:
    - linux
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SUBMODULE_DEPTH: 1
  script:
    - apt-get update && apt-get install -y cmake make gcc g++ clang
    - mkdir -p build-out && cd build-out
    - cmake ..
    - make

build-mac:
  tags:
    - mac
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SUBMODULE_DEPTH: 1
  script:
    - mkdir -p build-out && cd build-out
    - cmake ..
    - make

build-windows:
  tags:
    - windows
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SUBMODULE_DEPTH: 1
  script:
    - if (Test-Path build-out) { rmdir build-out -r -Force }
    - mkdir -p build-out
    - cd build-out
    - cmake ..
    - MSBuild.exe LOCAL_UTIL.sln
